<a href="https://colab.research.google.com/github/Igor-Minin/NN2021/blob/main/lr1_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

arr = np.arange(0, 5)

scalarArr = arr * 5

vectArr = arr * np.random.sample(5)

matrixArr = arr * np.arange(5, 30).reshape(5, 5)

print(scalarArr)
print(vectArr)
print(matrixArr)


[ 0  5 10 15 20]
[0.         0.25966972 1.99533074 2.81719322 1.39905629]
[[  0   6  14  24  36]
 [  0  11  24  39  56]
 [  0  16  34  54  76]
 [  0  21  44  69  96]
 [  0  26  54  84 116]]
