<a href="https://colab.research.google.com/github/Igor-Minin/NN2021/blob/master/lr2/lr2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
import numpy as np
import pandas as pd

npList = np.random.rand(4,5)
tfList = tf.constant(npList)
print("Numpy list:\n", npList)
print("Tensor list:\n", tfList)

print("Shape of tensor - ", tfList.shape)
print("Rank - ", tfList.ndim)
print("Size of tensor - ", tf.size(tfList).numpy())
axises = tfList.shape
counter = 0
for i in axises:
  print("Elements along axis", counter, "-", i)
  counter+=1

auxList = np.random.rand(4,5)
print("Auxiliary list for math operations:\n", auxList)

print("Addition scalar to tensor:\n", tfList+0.1)
print("Addition same dimensional list to tensor:\n", tfList+auxList)

print("Subtraction scalar from tensor:\n", tfList-0.1)
print("Subtraction same dimensional list from tensor:\n", tfList-auxList)

print("Division scalar on tensor:\n", tfList/2)
print("Division same dimensional list on tensor:\n", tfList/auxList)

print("Multiplication scalar on tensor:\n", tfList*2)
auxList = tf.reshape(auxList,shape = (5,4))
print("Multiplication same dimensional list on tensor:\n", tf.matmul(tfList,auxList))

d = {
    "one": pd.Series(np.arange(10, 20)),
    "two": pd.Series(np.arange(15, 30)),
    "three": pd.Series(np.arange(10,30))
}

df = pd.DataFrame(d)
print("Initial DataFrame:\n", df)

dfTfList = tf.convert_to_tensor(df)
print("Tensor DataFrame:\n", dfTfList)

print("--------CRUD--------")
print("Update and Delete operations are forbidden for tfList, due to immutability of tensor created by the .constant method")

tfListVar = tf.Variable([1,2,3,4,5])
print("Changeable tensor:\n", tfListVar)

tfListVar.assign([6,7,8,9,10])
print("Changed tensor:\n", tfListVar)



Numpy list:
 [[0.09481802 0.17902766 0.17927448 0.25876718 0.83870017]
 [0.76927689 0.31916086 0.49328463 0.00553388 0.59816548]
 [0.69391019 0.16224974 0.73517533 0.18203167 0.32976787]
 [0.67341837 0.74936164 0.41672018 0.98122527 0.4207159 ]]
Tensor list:
 tf.Tensor(
[[0.09481802 0.17902766 0.17927448 0.25876718 0.83870017]
 [0.76927689 0.31916086 0.49328463 0.00553388 0.59816548]
 [0.69391019 0.16224974 0.73517533 0.18203167 0.32976787]
 [0.67341837 0.74936164 0.41672018 0.98122527 0.4207159 ]], shape=(4, 5), dtype=float64)
Shape of tensor -  (4, 5)
Rank -  2
Size of tensor -  20
Elements along axis 0 - 4
Elements along axis 1 - 5
Auxiliary list for math operations:
 [[0.72592662 0.62328747 0.59791114 0.74414347 0.2373937 ]
 [0.93479604 0.50764169 0.9896106  0.10953774 0.27817363]
 [0.86049354 0.74881988 0.69499053 0.48465753 0.62557063]
 [0.87993244 0.25350919 0.13616961 0.13901133 0.09048033]]
Addition scalar to tensor:
 tf.Tensor(
[[0.19481802 0.27902766 0.27927448 0.35876718 0.